
import type { ServiceRecord } from './types';

export const serviceRecords: ServiceRecord[] = [
  {
    id: '1',
    date: '2025-10-30',
    technician: 'Derek',
    customer: 'CPW Properties',
    address: '14033 N South Shore Dr, Effingham, IL',
    phone: 'Not listed',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Service/Labor: $105.00',
    description: 'Customer called stating furnace will periodically get stuck in heating mode and not shut off at the thermostat. Inspected system. Cycled many times and could not duplicate issue. Discussed with Taylor. Unit heating as it should at this time.',
    total: 105.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Inspected furnace getting stuck in heating mode. Could not replicate the issue after multiple cycles. The unit is currently heating correctly.',
  },
  {
    id: '2',
    date: '2025-11-19',
    technician: 'Phil',
    customer: 'Los Amigos Carlyle',
    address: '5 Resort Ar, Carlyle, IL',
    phone: '(618) 844-5015',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '2',
    breakdown: 'Repair: $435.00',
    description: 'Installed new gas value and control knob food table, Reconnected gas lines and verified for leaks. Relit all fire pilots. All pilots verified. All good at this time.',
    total: 435.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Installed new gas valve and control knob on food table. Reconnected gas lines, checked for leaks, and relit all pilots. System functioning correctly.',
  },
  {
    id: '3',
    date: '2025-11-20',
    technician: 'Derek',
    customer: 'Jacob Kuhns',
    address: '6145 E 250th AVE, Mason, IL',
    phone: 'Not listed',
    model: 'ASUH12LMAS / AOUH12LMBS',
    serial: 'NXC014319 / MVQ003029',
    filterSize: 'N/A',
    freonType: 'R-410-A',
    laborHours: '5',
    breakdown: 'Quoted Price: $2,300.00',
    description: 'Installed new 12k btu heat pump unit hooked to provided fused disconnect. Installed POA on back of Building, spot for install leveled pad for outdoor unit, line hid Fan down to outside wall Cover and lineset drain line. System pressure tested, cycled and vacuum pulled. All working good at this time.',
    total: 2300.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Installed a new 12k BTU heat pump unit, including disconnect, pad, and lineset. System passed pressure test and is fully operational.',
  },
  {
    id: '4',
    date: '2025-11-24',
    technician: 'Derek',
    customer: 'Kathy Lilly',
    address: '14819 N 2005 st, Altamont, IL',
    phone: '(217) 821-1963',
    model: 'LG mirai split system',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Quoted Install: $3,142.00',
    description: 'Installed new 9Kbtu LG mirai split system in bedroom as quoted. Ran conduit and installed new power wire, new breaker in main panel, new pad, whip & disconnect, conduit protector, and surge protector. Cycled and tested all operations. All good.',
    total: 3142.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Installed a new 9k BTU LG split system in the bedroom. Work included new electrical, pad, disconnect, and surge protector. System tested and working correctly.',
  },
  {
    id: '5',
    date: '2025-11-24',
    technician: 'Derek',
    customer: 'Arcolas Grocery',
    address: '117 W. Washington St, Arcola, IL',
    phone: '217-268-3007',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'R-134 A',
    laborHours: '2',
    breakdown: 'Service: $75; Labor: $105; Hard Start Kit: $68; Misc: $21',
    description: 'Customer stated prep table had not been cooling. Found failed start delay. Replaced with new 3/1 hard start kit. Cycled unit, cooling good at this time.',
    total: 269.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Repaired a prep table that was not cooling by replacing a failed start delay with a new hard start kit. The unit is now cooling properly.',
  },
  {
    id: '6',
    date: '2025-11-25',
    technician: 'Phil',
    customer: 'Los Amigos Carlyle',
    address: '5 Resort Drive, Carlyle, IL',
    phone: '(618) 844-5015',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Parts & Labor: $986.00',
    description: 'Customer called with multiple issues. Cooler door leaking air and not sealing properly. Adjusted latch and door hinges, installed new rubber seals, siliconed center stainless cap on wall panel seams. Removed vent hoods, sealed multiple holes that were allowing grease to leak, cleaned pieces and re-installed. Also installed drain for left side of exhaust hood. Used stainless steel sealant to ensure there are no leaks. Also installed new wall supports on walk-in cooler walls to keep them from moving too much.',
    total: 986.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Addressed multiple issues: fixed cooler door seal, repaired grease leaks in exhaust hood by sealing holes, installed a new drain, and added wall supports for the walk-in cooler.',
  },
  {
    id: '7',
    date: '2025-11-25',
    technician: 'Derek',
    customer: 'Noah Flowers',
    address: '900 N Main, Saint Elmo, IL',
    phone: '618-267-7839',
    model: 'MEA951X060 / MEASAC 3036A',
    serial: '25274 / 250 22K BMFF',
    filterSize: 'Not listed',
    freonType: 'R-454 B',
    laborHours: '4',
    breakdown: 'Quoted Price: $6,135.00',
    description: 'Replaced both furnace and air conditioner with matching evop coil sets. New drain, vents, power disconnect pad, whip, and rehooked gas line. Installed drip leg for gas line, installed control and kwires, rehooked to gas supply. Cycled unit, heating good at this time.',
    total: 6135.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Replaced the furnace and air conditioner with a matching coil set. Installation included new drain, vents, disconnect, pad, and gas line connections. System is heating properly.',
  },
  {
    id: '8',
    date: '2025-11-28',
    technician: 'Derek',
    customer: 'Herrick Fire Protection',
    address: '9 Broadway st, Herrick, IL',
    phone: '618-428-5454',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '1.08',
    breakdown: 'Service/Labor: $158.00',
    description: 'Cycled furnace upon arrival. Found failing to rectify flame for intermittent pilot. Removed pilot assembly. Cleaned orifice and flame sensor ignitor. Reinstalled and cycled heat again. Cycled multiple times to verify proper operation. All good and heating at this time.',
    total: 158.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Addressed furnace flame failure by cleaning the pilot assembly, orifice, and flame sensor. The furnace now operates correctly after multiple successful cycles.',
  },
  {
    id: '9',
    date: '2025-11-29',
    technician: 'Phil',
    customer: 'Joes Pizza',
    address: '4 Centa Court, St. Elmo, IL',
    phone: '618-979-9511',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Fuel/Misc: $6,618.00; Labor: $295.00; Fittings: $130.00',
    description: 'Outstanding Invoices 2025 Past due. Paid up for 2025.',
    total: 7043.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Customer settled outstanding past-due invoices for 2025. Account is now paid up.',
  },
  {
    id: '10',
    date: '2025-11-30',
    technician: 'Phil',
    customer: 'CPW',
    address: '14034 North Remony Lane, Effingham, IL',
    phone: '217-663-6699',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '1',
    breakdown: 'Labor: $267.00; TC: $69.00',
    description: 'Customer stated pilot light would not stay lit. Checked unit and found pilot would not stay lit. Replaced thermocouple. Came back next day, found pilot light working. Inspected unit and found all good at this time.',
    total: 336.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Repaired a pilot light that would not stay lit by replacing the thermocouple. The unit is now functioning correctly.',
  },
  {
    id: '11',
    date: '2025-12-01',
    technician: 'Derek',
    customer: 'Caleb Saruer',
    address: 'Moon St, Herrick, IL',
    phone: '217-240-8424',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '3.25',
    breakdown: 'Quoted Install: $700.00',
    description: 'Removed existing furnace and installed new customer provided gas furnace. Rehooked to gas vent. Removed evaporator coil and did not reinstall per customer request. Cycled and tested new heating gas furnace. Checked gas pressure. All ok.',
    total: 700.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Installed a customer-provided gas furnace, re-hooking gas and vent lines. The evaporator coil was removed per request. The new furnace is operating correctly.',
  },
  {
    id: '12',
    date: '2025-12-01',
    technician: 'Phil',
    customer: 'El Cactus Mexican Grill',
    address: '200 W Main st, Olney, IL',
    phone: '(618) 395-7000',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Labor: $105; Trip: $75; Misc: $69.00',
    description: 'Cycled and inspected furnace upon arrival. Cleared and blew out drain switch tubing. Also found thermostat not securely fastened to wall plate; secured thermostat. Found vent piping not properly pitched and/or supported, holding water. Sloped properly and secured in place. Cycled and tested, all good at this time.',
    total: 349.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Serviced furnace: cleared drain tubing, secured thermostat, and corrected vent pipe slope to fix water issue. System is now working properly.',
  },
  {
    id: '13',
    date: '2025-12-03',
    technician: 'Derek',
    customer: 'Arcola Hispanic',
    address: '117 W Washington St, Arcola, IL',
    phone: '217-268-3007',
    model: 'GDC- 69-HC',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Unit Price: $3,507.00',
    description: '(1) Avantco GDC- 69-HC 74 1/4" 3 door Swing Glass door merchandiser',
    total: 3507.0,
    status: 'Estimate',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Provided an estimate for one Avantco GDC-69-HC 74 1/4" 3-door swing glass door merchandiser.',
  },
  {
    id: '14',
    date: '2025-12-03',
    technician: 'Phil',
    customer: 'El Cactus',
    address: '200 W Main St, Olney, IL',
    phone: '618-395-7000',
    model: 'GDC-23-HC / HBB-95-HC',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Units: $3,899.00',
    description: '(1) Avantco GDC-23-HC 28 3/8" Swing Glass Door Merchandiser (1) Avantco HBB-95-HC Black Horizontal Bottle Cooler',
    total: 3899.0,
    status: 'Estimate',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Provided an estimate for one Avantco GDC-23-HC glass door merchandiser and one Avantco HBB-95-HC horizontal bottle cooler.',
  },
  {
    id: '15',
    date: '2025-12-05',
    technician: 'Phil',
    customer: 'CPW',
    address: '106 N Vine st, Effingham, IL',
    phone: '217-663-6699',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '0.5',
    breakdown: 'Service Charge: $89.00',
    description: 'Customer stated furnace not heating. Thermostat was reading 32F. Inspected unit and found flame sensor needed to be cleaned. Pulled, cleaned, and reinstalled. Unit heating at this time.',
    total: 89.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Serviced a furnace that was not heating. Cleaned the flame sensor, resolving the issue. The unit is now operating correctly.',
  },
  {
    id: '16',
    date: '2025-12-08',
    technician: 'Derek',
    customer: 'NV Spa',
    address: '108 N Main st, Altamont, IL',
    phone: '(217) 821-4324',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '0.92',
    breakdown: 'Heat Tune Up: $99; Filter: -$10.00',
    description: 'Heat tune-up. Cycled heat, inspected furnace to verify operation. Cleaned and vacuumed blower and compartments. Tightened all wiring connectors. Replaced air filter with customer provided one. Removed and cleaned tubing, flame sensor, pressure switch, and all condensate lines. Added cleaner to condensate pump. Cycled heat and checked temp rise. Verified proper operation. All good.',
    total: 89.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Performed a furnace heat tune-up, including cleaning multiple components, tightening electrical connections, and replacing the air filter. The system is operating correctly.',
  },
  {
    id: '17',
    date: '2025-12-09',
    technician: 'Phil',
    customer: 'Lantacomp',
    address: '619 S Third St, Brownstown, IL',
    phone: '(618) 427-3242',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '0.92',
    breakdown: 'Service Labor: $131.00',
    description: 'Received call that heaters were not working properly. Inspected unit and found it short cycling due to a thermostat issue. Adjusted cycle rate on the wall and unit seemed to be working fine. Advised customer to monitor and replace thermostat if issue persists.',
    total: 131.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Addressed a short-cycling heater by adjusting the thermostat cycle rate. Advised customer to monitor and potentially replace the thermostat.',
  },
  {
    id: '18',
    date: '2025-12-09',
    technician: 'Derek',
    customer: 'Tonny\'s China Buffet',
    address: '825 New York Dr, Vandalia, IL',
    phone: '(573) 380-1426',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '1',
    breakdown: 'Service Labor: $158.00',
    description: 'Unit was making ice upon arrival. Inspected ice machine and found water filter dirty. Will order filter and schedule time to perform deep clean of machine.',
    total: 158.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Inspected ice machine and found a dirty water filter. A new filter will be ordered and a deep cleaning scheduled for a later date.',
  },
  {
    id: '19',
    date: '2025-12-09',
    technician: 'Derek',
    customer: 'Jake Sapp',
    address: '2654 N 2075 st, Beecher City, IL',
    phone: '(618) 292-1960',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '0.92',
    breakdown: 'Service Labor: $111.00',
    description: 'Inspected tube heater upon arrival. Found shuttle heat. Removed and cleaned flame sensor and blew out pressure switch tubing. Cycled unit with no issues. Unit is heating and all good at this time.',
    total: 111.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Serviced a tube heater by cleaning the flame sensor and pressure switch tubing. The unit is now heating without issues.',
  },
  {
    id: '20',
    date: '2025-12-09',
    technician: 'Phil',
    customer: 'Los Amigos',
    address: '1611 Veterans Ave, Vandalia, IL',
    phone: '618-283-4110',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '1.5',
    breakdown: 'Service Labor: $315.00',
    description: 'Customer stated that the exhaust hood in the kitchen was not working. They replaced the motor. Adjusted brackets and belt tension. Inspected the unit and found motor hardly moving. Pulled cover and found all good.',
    total: 315.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Addressed a non-working kitchen exhaust hood. After customer replaced motor, adjusted brackets and belt tension. Inspected and confirmed proper operation.',
  },
  {
    id: '21',
    date: '2025-12-12',
    technician: 'Phil',
    customer: 'Los Amigos',
    address: '205 N Keller dr, Effingham, IL',
    phone: '217-994-9143',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: '404A',
    laborHours: '0.75',
    breakdown: 'Labor: $420; Freon: $185; Misc: $183',
    description: 'Took ice machine apart to check for leaks. Found leaks on call wor and welds on unit. Recharged with 20oz. of R-404A. Fan cycling switch replaced also. Pulled vacuum. Cleared ice. Machine working good at this time.',
    total: 788.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Repaired leaks in an ice machine, replaced the fan cycling switch, and recharged with R-404A refrigerant. The machine is now working correctly.',
  },
  {
    id: '22',
    date: '2025-12-15',
    technician: 'Jake',
    customer: 'Hefley Associates',
    address: '2025 Broadway st, Mt Vernon, IL',
    phone: '618-842-2102',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: '16x1',
    freonType: 'Not listed',
    laborHours: '2.5',
    breakdown: 'Labor: $416; Service Fee: $75; Misc: $69',
    description: 'Upon arrival found one unit off on error codes. Upon inspecting primary & secondary heat exchangers, it was clear both were caked with dry drywall dust. Pulled blower motor for wash, rinsed primary & secondary & reassembled unit. Upon completion supply temp held at 135°F & unit satisfied.',
    total: 560.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Cleaned drywall dust from clogged primary and secondary heat exchangers and blower motor. After reassembly, the unit is holding temperature and operating correctly.',
  },
  {
    id: '23',
    date: '2025-12-15',
    technician: 'Phil',
    customer: 'El Cactus',
    address: '300 Main Albion, IL',
    phone: '618-445-9222',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'MO99',
    laborHours: 'N/A',
    breakdown: 'Parts: $360; Freon: $680; Fee: $75; Labor: $840',
    description: 'Previous visit found walk-in cooler at 65°F. Inspected system and found no freon. Pressurized system and found leak in low pressure control tube. Cut off, welded new fitting, pressure tested with nitrogen. Pulled vacuum to 300 microns, filled system with 8lb of MO99 refrigerant. Cycled system, cooling good. Installed new condenser fan motor on unit #1 and new evap fan motor on unit #2.',
    total: 1955.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Repaired walk-in cooler leak, recharged with refrigerant, and replaced condenser and evaporator fan motors on two units. The cooler is now operating correctly.',
  },
  {
    id: '24',
    date: '2025-12-16',
    technician: 'Derek',
    customer: 'Christian Rental',
    address: '513 W. Franklin, Effingham, IL',
    phone: '217-663-1123',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: '16x20x1',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Total Repair & Service: $456.00',
    description: 'Arrived and found rollouts cut. After rewiring, found no ground to unit. After grounding unit, fan was flashing. Installed new flashing. Also found gas pressure at 4.5", lowered to 3.5". When left job, unit was running.',
    total: 456.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Repaired furnace by fixing wiring, establishing a proper ground, and adjusting gas pressure. The unit was running upon departure.',
  },
  {
    id: '25',
    date: '2025-12-17',
    technician: 'Phil',
    customer: 'Morgan Myers Rental',
    address: '1109 Mulberry Rd, Mulberry Grove, IL',
    phone: '260-273-9995',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '1.67',
    breakdown: 'Fee: $75.00; Labor: $190.00',
    description: 'Arrived and gas was off and unit was not operational. After turning gas on, discovered two gas leaks. While lighting pilot, discovered the pilot had way too much fuel going to it, so adjusted set screw properly. Fired leaks and limit connection. Unit was operating as it should.',
    total: 265.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Repaired gas leaks and adjusted pilot light fuel supply on a non-operational furnace. The unit is now working correctly.',
  },
  {
    id: '26',
    date: '2025-12-18',
    technician: 'Derek',
    customer: 'Tonny\'s China Buffet',
    address: '825 New York Dr, Vandalia, IL',
    phone: '(573) 380-1426',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Water Filter: $105.00',
    description: 'Came to clean ice machine and replace water filter. Tonny asked if we would just change filter and come back to clean machine as restaurant is too busy to discard ice today. Replaced water filter. Will reschedule cleaning.',
    total: 105.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Replaced the water filter on an ice machine at the customer\'s request. A full cleaning of the machine will be rescheduled for a later date.',
  },
  {
    id: '27',
    date: '2025-12-22',
    technician: 'Phil',
    customer: 'Los Amigos',
    address: '5 resort Dr, Carlyle, IL',
    phone: '618-844-5015',
    model: 'Hoshizaki 1m515',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '6',
    breakdown: 'Total: $1,740.00',
    description: 'Upon arrival, unit in Fenton but had a squeal from the water pump. Looked at Hoshizaki 1m515 that had a "whine". Took pump out but the spool was stuck. Contacted supplier in Fenton, MO and contacted customer with price. Installed new motor and hoses. De-limed ice machine.',
    total: 1740.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Replaced a noisy water pump motor and hoses on a Hoshizaki ice machine. Also performed a de-liming service. The machine is now operating correctly.',
  },
  {
    id: '28',
    date: '2025-12-29',
    technician: 'Jake',
    customer: 'Altamont VFW',
    address: '302 W Cumberland Rd, Altamont, IL',
    phone: '(618) 483-6344',
    model: 'Carrier 58MCA 100-20',
    serial: '2895A11529',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '0.75',
    breakdown: 'Labor: $105; Capacitor: $49',
    description: 'Heat not working upon arrival. Inspected and found a failed blower capacitor. Replaced capacitor, after ignition motor tested good. Cycled unit multiple times. Unit is heating with no failures.',
    total: 154.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Fixed a no-heat issue by replacing a failed blower capacitor. The furnace is now heating correctly after multiple successful tests.',
  },
  {
    id: '29',
    date: '2025-12-30',
    technician: 'Phil',
    customer: 'Ronaldo Rental',
    address: '210 Vine st, Mount Carmel, IL',
    phone: '618-863-1112',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: '1.5',
    breakdown: 'Labor: $178; Fee: $75',
    description: 'Arrived to find furnace disassembled and high limit switch popped. Popped off the manual resets to close the limits. Re-assembled furnace. Furnace is operating and working as of 4:30pm.',
    total: 253.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Reset a popped high limit switch on a disassembled furnace. After reassembly, the furnace is now operating correctly.',
  },
  {
    id: '30',
    date: '2025-12-30',
    technician: 'Phil',
    customer: 'El Cactus',
    address: '200 W. Main, Olney, IL',
    phone: '618-345-7000',
    model: 'CME7656RS-32F',
    serial: '703384-0354144',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Valve: $231; Labor: $315; Fee: $75',
    description: 'Arrived to machine off. Did an inspection of unit and noted water valve seemed dropped. Disassembled valve to clean. Reran unit until part arrived for replacement. Replaced Parts and unit is operational.',
    total: 621.0,
    status: 'Paid',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Repaired an ice machine by cleaning and then replacing a faulty water valve. The unit is now operational.',
  },
  {
    id: '31',
    date: '2026-01-01',
    technician: 'Jake',
    customer: 'Marsha Nolan',
    address: '212 S. Popular, Farina, IL',
    phone: 'Not listed',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Cleanup: $0.00',
    description: 'Customer stated No heat. Found large amount of mouse droppings build up on burners. Cleaned unit and burners and reassembled unit. Unit set and was operating when departed.',
    total: 0.0,
    status: 'No Charge',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Resolved a no-heat call by cleaning a significant amount of mouse droppings from the furnace burners. The unit is now operating correctly.',
  },
  {
    id: '32',
    date: '2026-01-08',
    technician: 'Jake',
    customer: 'Hefley Assoc.',
    address: '2025 Broadway st, Mt Vernon, IL',
    phone: '618-842-2902',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Quoted Total: $560.00',
    description: 'Returned to complete full disassembly and cleaning of unit #2. Found primary and secondary clogged with drywall dust as expected. Completely washed coils and caulked all unsealed ducts. Finished job, unit is running as it should.',
    total: 560.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1zj77AB8pqXzkzh03ggXwzn3UAnd2zXDB/view?usp=drive_link',
    summary: 'Completed cleaning of a second unit. Washed coils clogged with drywall dust and sealed ducts. The unit is now running properly.',
  },
  {
    id: '33',
    date: '2026-01-08',
    technician: 'Jake',
    customer: 'Joe\'s Godfrey',
    address: '5775 Godfrey Rd, Godfrey, IL',
    phone: '618-433-8000',
    model: 'Somerset Dough Roller',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Labor: $105; Fee: $75',
    description: 'Arrived for install of Somerset dough roller switch panel. Installed panel. Machine functioned as should when departed.',
    total: 180.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Installed a new switch panel on a Somerset dough roller. The machine is now functioning correctly.',
  },
  {
    id: '34',
    date: '2026-01-09',
    technician: 'Jake',
    customer: 'Marsha Nolan',
    address: '212 S. Popular st, Farina, IL',
    phone: 'Not listed',
    model: 'WGFDC 090016-10',
    serial: '3060672697',
    filterSize: 'Not listed',
    freonType: 'Not listed',
    laborHours: 'N/A',
    breakdown: 'Part: $141; Labor: $105; Fee: $75',
    description: 'Arrived to a no heat call. Inspected unit, realized unit had no igniter. Tested for 120v to igniter and had voltage. Pulled and noticed it was broken. Next morning, located one in Murphysboro, returned to customer 1-9-26, installed, reassembled unit, cycled and at 2:20pm unit was operational.',
    total: 321.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Resolved a no-heat call by replacing a broken igniter. After sourcing the part, the furnace was repaired and is now operational.',
  },
  {
    id: '35',
    date: '2026-01-12',
    technician: 'Jake',
    customer: 'Ronaldo Gonatez',
    address: '16218 N Country Estates Rd, Effingham, IL',
    phone: '618-863-1112',
    model: 'GMUC9507044BA',
    serial: '1401298268',
    filterSize: '16x25 lemox',
    freonType: '410 A',
    laborHours: '1.5',
    breakdown: 'Labor: $223; Fee: $75',
    description: 'Began diagnosis with the downstairs furnace (unit #2). Verified no signal from the thermostat. After tracing the wiring found that the condensate pump float was stuck, interrupting the control voltage. Customer advised to replace pump. Inspected unit #1 then lit pilot. Identified dirty burners and box so shut unit down, disassembled burner bar and cleaned unit. Customer returned with new condensate pump for unit #2, installed and checked operation. Everything functioned correctly post-cleaning.',
    total: 298.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Serviced two furnaces. Replaced a stuck condensate pump on one unit and cleaned dirty burners on the other. Both systems are now functioning correctly.',
  },
  {
    id: '36',
    date: '2026-01-12',
    technician: 'Derek',
    customer: 'Los Amigos',
    address: '205 N Keller Dr, Effingham, IL',
    phone: '217-994-9143',
    model: 'Not listed',
    serial: 'Not listed',
    filterSize: 'Not listed',
    freonType: '404A',
    laborHours: '0.83',
    breakdown: 'Labor: $105; Freon: $95',
    description: 'Inspected prep table upon arrival. Unit cycling and satisfying on thermostat. Monitored unit. Cooling ok at this time. Topped off with R404A freon.',
    total: 200.0,
    status: 'Owed',
    fileUrl: 'https://drive.google.com/file/d/1BmEjZxWeStnj8JRrR9_K2SF79pyARuqb/view?usp=drive_link',
    summary: 'Inspected a prep table that was cycling correctly. Topped off the system with R404A refrigerant. The unit is cooling properly.',
  },
];
